baseURL = 'https://orion551.github.io/itcorner/'
languageCode = 'it-IT'
title = 'CISF26'
theme = 'cisf26-theme'
[caches]
  [caches.images]
    dir = ':cacheDir/images'

[[menus.main]]
  identifier = "users-solid"
  name = "Chi Siamo"
  pageRef = "/about-us/"
  weight = 20
  [menus.main.params]
    show_desktop = true
    desktop_sort = 7
    icon = "fa-users"
    bottombar = false
[[menus.main]]
  identifier = "building-solid"
  name = "Strutture"
  pageRef = "/locations/"
  weight = 30
  [menus.main.params]
    show_desktop = true
    desktop_sort = 6
    icon = "fa-building-columns"
    bottombar = false
[[menus.main]]
  identifier = "clipboard-user-solid"
  name = "Ospiti"
  pageRef = "/guests/"
  weight = 40
  [menus.main.params]
    show_desktop = true
    desktop_sort = 5
    icon = "fa-clipboard-user"
    bottombar = false
[[menus.main]]
  identifier = "calendar-solid"
  name = "Programma"
  pageRef = "/schedule/"
  weight = 50
  [menus.main.params]
    show_desktop = true
    desktop_sort = 2
    icon = "fa-calendar-days"
    bottombar = true
    mobile_sort = 2
[[menus.main]]
  identifier = "handshake-solid"
  name = "Partners"
  pageRef = "/partners/"
  weight = 60
  [menus.main.params]
    show_desktop = true
    desktop_sort = 1
    icon = "fa-handshake"
    bottombar = true
    mobile_sort = 1
[[menus.main]]
  identifier = "signature-solid"
  name = "Iscriviti"
  pageRef = "/subscriptions/"
  weight = 70
  [menus.main.params]
    show_desktop = true
    desktop_sort = 3
    icon = "fa-file-signature"
    bottombar = true
    mobile_sort = 3
[[menus.main]]
  identifier = "support-solid"
  name = "Sostienici"
  pageRef = "/support-us/"
  weight = 80
  [menus.main.params]
    show_desktop = true
    desktop_sort = 4
    icon = "fa-hand-holding-heart"
    bottombar = true
    mobile_sort = 4

[params]
    siteTitle = "CISF26"
    image = "images/cisf.svg"
    alt = 'CISF26 Logo'